"""changed one collumn in Books. Now it is borrowed_id - int

Revision ID: 3a508c0f6549
Revises: 4d8c82dcadab
Create Date: 2020-09-13 10:26:18.460557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a508c0f6549'
down_revision = '4d8c82dcadab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('borrowed_id', sa.Integer(), nullable=True))
    op.drop_column('books', 'borrowed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('borrowed', sa.BOOLEAN(), nullable=True))
    op.drop_column('books', 'borrowed_id')
    # ### end Alembic commands ###
